language: node_js
node_js:
- '4'
- stable
services: redis-server
deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: PObgydaS9MLOCtlg8Apjwidt7AOs3Sa0A2KTB1AB+VoqJcFIVFyY9oQ6B8w/57/AlzO6s3SuxU3W4gTDqOrDM7LwCkh6QLeBt1VMfAkKaoxnii68BJ4tS8YHKMBrxfuda0JDmZvclkCWakNkh8yuP6W4IbescAinn42so24c4uOWYh2iBadzYZKwsVwgXETjW6G5wJ/xSGIr3LDM+zyo9lBLQeaZmKisw5Koq0/xJ7ypwKVuLjxGCL4uKmdwaedCnQWeca9JXLi7z1dt/sItrxkABCm4dl93zGk29lgh4oPGLOYEtPf1ePLLPxCp0Q5AxZPak+wg6qGH6QHOHSoJLSYSytYgNpaBVeYJEIyY8GWM1lCnWmmWVRTZEyl0YQa9Rwudb63Z/dhxwo0i0NPYnGhYatAO8dH+OD5J0mRsc2ZHkKyIte2I8xC10I4ks5S3aP9PAhCq8SJGC4FPN06PFHZArbfdHESTnpRIgcctt1NqNYWDvQjWFlYKGk66DQQCx/R9fqK9gr+G5EomeiCB+etVFusF+0ylO3txBfrhUhlWj3loYo+5PAy4t75KhpRqrYpScskgx2f2QKTJVYONo/+VLMNJM2iyMfWnmzqFIn3QtjSrceupZXMVTwB69M+H8nQWKGIt4cu25Lv0mSrSC2QnereHIgaeDtwCH7AfrRk=
  on:
    tags: true
    repo: trailsjs/trailpack-pubsub
    node: stable
